services:
  node1:
    build: .
    container_name: node1
    environment:
      PORT: "8088"
    ports:
      - "9088:8088"   # Service port
      - "9188:8089"   # Discovery port
    networks:
      - mynetwork

  node2:
    build: .
    container_name: node2
    environment:
      PORT: "8089"
    ports:
      - "9089:8089"   # Service port
      - "9189:8089"   # Discovery port
    networks:
      - mynetwork

  node3:
    build: .
    container_name: node3
    environment:
      PORT: "8090"
    ports:
      - "9090:8090"   # Service port
      - "9190:8089"   # Discovery port
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge