version: '3'

services:
  discovery:
    build: 
      context: . 
      dockerfile: DockerfileDiscovery
    container_name: discovery
    ports:
      - "9000:8000"   # Discovery service API port
    networks:
      - mynetwork
    environment:
      - PORT=8000
      - SERVICE_TYPE=discovery

  node1:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: node1
    environment:
      - PORT=8088
      - DISCOVERY_URL=http://discovery:8000
      - NODE_ID=node1
    ports:
      - "9088:8088"   # Service port
    networks:
      - mynetwork
    depends_on:
      - discovery

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node2
    environment:
      - PORT=8089
      - DISCOVERY_URL=http://discovery:8000
      - NODE_ID=node2
    ports:
      - "9089:8089"   # Service port
    networks:
      - mynetwork
    depends_on:
      - discovery

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node3
    environment:
      - PORT=8090
      - DISCOVERY_URL=http://discovery:8000
      - NODE_ID=node3
    ports:
      - "9090:8090"   # Service port
    networks:
      - mynetwork
    depends_on:
      - discovery

networks:
  mynetwork:
    driver: bridge
