version: '3.8'
services:
  node1:
    image: assignment-advance-node1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8081
      - DISCOVERY_PORT=8089
      - PEERS=node2:8082,node3:8083
    networks:
      - mynetwork
    ports:
      - "8081:8081"

  node2:
    image: assignment-advance-node2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8082
      - DISCOVERY_PORT=8089
      - PEERS=node1:8081,node3:8083
    networks:
      - mynetwork
    ports:
      - "8082:8082"

  node3:
    image: assignment-advance-node3
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8083
      - DISCOVERY_PORT=8089
      - PEERS=node1:8081,node2:8082
    networks:
      - mynetwork
    ports:
      - "8083:8083"

networks:
  mynetwork:
    driver: bridge